agent:
  name: "sys-info-agent"
  interval_seconds: 5

collectors:
  cpu: true
  ram: true
  disk: true

services:
  - name: "nginx"
    host: "127.0.0.1"
    port: 80
  - name: "mysql"
    host: "127.0.0.1"
    port: 3306
